import crypto from 'node:crypto'; import fs from 'node:fs/promises'; import path from 'node:path'; import pdf from 'pdf-parse'; import mammoth from 'mammoth'; import type {Claim,EvidenceKind,SourceDocument} from './types'
const DATA=path.join(process.cwd(),'data','proofmesh','uploads')
export async function sha256(bytes:Buffer){return crypto.createHash('sha256').update(bytes).digest('hex')}
export function inferKind(name:string):EvidenceKind{const n=name.toLowerCase();if(n.includes('purchase')||n.includes('po'))return'purchase_order';if(n.includes('invoice')||n.includes('inv'))return'invoice';if(n.includes('delivery')||n.includes('dispatch')||n.includes('dn'))return'delivery_note';if(n.includes('certificate')||n.includes('cert'))return'certificate';if(n.includes('company')||n.includes('profile'))return'company_profile';return'other'}
export async function extractText(name:string,mime:string,bytes:Buffer):Promise<{text:string;pageCount?:number}>{if(mime==='application/pdf'||name.toLowerCase().endsWith('.pdf')){const r=await pdf(bytes);return{text:r.text,pageCount:r.numpages}}if(mime.includes('word')||name.toLowerCase().endsWith('.docx')){const r=await mammoth.extractRawText({buffer:bytes});return{text:r.value}}if(mime.startsWith('text/')||/\.(txt|csv|json|md)$/i.test(name))return{text:bytes.toString('utf8')};throw new Error('Unsupported file type. Use PDF, DOCX, TXT, CSV, JSON or MD.')}
function numberAfter(re:RegExp,text:string){const m=text.match(re);return m?Number(m[1].replace(/,/g,'')):null} function dateAfter(re:RegExp,text:string){const m=text.match(re);return m?m[1]:null}
function firstEntity(text:string){const m=text.match(/(?:supplier|vendor|company|seller)\s*[:\-]\s*([^\n,]+)/i);return m?.[1]?.trim()||null}
export function extractClaims(doc:SourceDocument,text:string):Claim[]{const claims:Claim[]=[];const add=(type:Claim['type'],subject:string,predicate:string,value:string|number,unit?:string)=>claims.push({id:crypto.randomUUID(),sourceId:doc.id,sourceName:doc.name,type,subject,predicate,value,unit,confidence:.92});const entity=firstEntity(text);if(entity)add('entity','supplier','name',entity);const q=numberAfter(/(?:quantity|qty|units?|ordered|delivered|billed)\s*[:#=-]?\s*([\d,]+)/i,text);if(q!==null)add('quantity','document','quantity',q,'units');const price=numberAfter(/(?:unit\s*price|price\s*per\s*unit|rate)\s*[:#=-]?\s*[₹$€]?\s*([\d,.]+)/i,text);if(price!==null)add('price','item','unit_price',price);const total=numberAfter(/(?:grand\s*total|invoice\s*total|total\s*amount|total)\s*[:#=-]?\s*[₹$€]?\s*([\d,.]+)/i,text);if(total!==null)add('total','document','total',total);const id=text.match(/(?:invoice\s*(?:no|number)|po\s*(?:no|number)|order\s*(?:id|number)|document\s*id)\s*[:#-]?\s*([A-Z0-9\-\/]+)/i);if(id)add('identifier','document','identifier',id[1]);const date=dateAfter(/(?:invoice\s*date|order\s*date|delivery\s*date|date)\s*[:#-]?\s*([0-9]{1,4}[\/\-][0-9]{1,2}[\/\-][0-9]{1,4})/i,text);if(date)add('date','document','date',date);const valid=dateAfter(/(?:valid\s*(?:until|through)|expiry|expires)\s*[:#-]?\s*([^\n]+)/i,text);if(valid)add('validity','certificate','valid_until',valid.trim());if(claims.length===0)add('text','document','content',text.slice(0,500).replace(/\s+/g,' ').trim());return claims}
export async function persistUpload(id:string,name:string,bytes:Buffer){await fs.mkdir(DATA,{recursive:true});await fs.writeFile(path.join(DATA,id+'-'+name.replace(/[^a-zA-Z0-9._-]/g,'_')),bytes)}
