'use client'
import {useState} from 'react'
import {useRouter} from 'next/navigation'

const steps=[['01','COLLECT','Bring the evidence together'],['02','EXTRACT','Turn documents into claims'],['03','VERIFY','Cross-check with deterministic rules'],['04','INVESTIGATE','Resolve what the documents cannot']]

export function ProofMeshDashboard(){
 const [files,setFiles]=useState<File[]>([]),[name,setName]=useState('Supplier evidence review'),[busy,setBusy]=useState(false),[error,setError]=useState('');const router=useRouter()
 async function analyze(){if(!files.length)return;setBusy(true);setError('');try{const f=new FormData();f.append('caseName',name);files.forEach(x=>f.append('files',x));const r=await fetch('/api/proofmesh/analyze',{method:'POST',body:f});const data=await r.json();if(!r.ok)throw new Error(data.error||'Analysis failed');router.push(`/case/${data.id}`)}catch(e){setError(e instanceof Error?e.message:'Analysis failed');setBusy(false)}}
 return <main className="min-h-screen overflow-hidden bg-mist text-ink">
  <div className="hero-grid pointer-events-none fixed inset-0 opacity-60"/><div className="orb orb-one pointer-events-none fixed"/><div className="orb orb-two pointer-events-none fixed"/>
  <header className="sticky top-0 z-30 border-b border-ink/10 bg-mist/80 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><div><div className="font-display text-xl font-semibold tracking-tight">Proof<span className="text-pulse">Mesh</span></div><div className="font-mono text-[10px] uppercase tracking-[.18em] text-ink/50">Decision-aware evidence intelligence</div></div><div className="flex items-center gap-2 rounded-full border border-ink/10 bg-white/50 px-3 py-2 font-mono text-[10px] uppercase tracking-[.14em] text-ink/60"><span className="relative flex h-2 w-2"><span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-glow opacity-75"/><span className="relative inline-flex h-2 w-2 rounded-full bg-glow"/></span> verification online</div></div></header>
  <section className="relative mx-auto grid max-w-7xl items-center gap-12 px-6 py-16 lg:grid-cols-[1.05fr_.95fr] lg:py-24">
   <div className="reveal-up"><div className="inline-flex rounded-full border border-pulse/20 bg-pulse/5 px-3 py-1 font-mono text-[10px] uppercase tracking-[.15em] text-pulse">Evidence → verification → human decision</div><h1 className="mt-6 font-display text-5xl font-semibold leading-[.9] tracking-[-.06em] md:text-7xl">Don't just trust the document.<br/><span className="gradient-text">Trace the proof.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-ink/65">ProofMesh turns fragmented business documents into traceable claims, catches contradictions deterministically, and sends unresolved questions to a human-approved CALL-E investigation.</p><div className="mt-8 flex flex-wrap gap-2 text-xs font-mono"><span className="chip">PDF / DOCX / TXT</span><span className="chip">SHA-256 provenance</span><span className="chip">Rule-based verification</span><span className="chip">Human-gated calls</span></div><div className="mt-9 rounded-2xl border border-ink/10 bg-white/45 p-4 backdrop-blur"><div className="font-mono text-[10px] uppercase tracking-[.15em] text-ink/40">How ProofMesh decides</div><div className="mt-2 grid gap-2 text-sm sm:grid-cols-3"><div><b>AI</b><span className="text-ink/55"> extracts claims</span></div><div><b>Rules</b><span className="text-ink/55"> verify contradictions</span></div><div><b>Humans</b><span className="text-ink/55"> make the decision</span></div></div></div></div>
   <div className="reveal-up reveal-delay relative"><div className="absolute -inset-8 rounded-[2.5rem] bg-pulse/10 blur-3xl animate-breathe"/><div className="relative rounded-[2rem] border border-ink/10 bg-white/75 p-6 shadow-2xl shadow-ink/10 backdrop-blur-xl transition-transform duration-500 hover:-translate-y-1"><div className="flex items-start justify-between"><div><div className="font-mono text-[10px] uppercase tracking-[.15em] text-ink/45">New verification case</div><input value={name} onChange={e=>setName(e.target.value)} className="mt-2 w-full bg-transparent font-display text-2xl font-semibold outline-none"/></div><div className="sparkle grid h-11 w-11 place-items-center rounded-2xl bg-ink text-white">✦</div></div><label className="upload-zone mt-7 block cursor-pointer rounded-2xl border-2 border-dashed border-ink/15 bg-mist/80 p-9 text-center transition hover:border-pulse/50 hover:bg-pulse/[.03]"><input multiple type="file" accept=".pdf,.docx,.txt,.csv,.json,.md" className="hidden" onChange={e=>setFiles(Array.from(e.target.files||[]))}/><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl border border-ink/10 bg-white text-2xl text-pulse shadow-sm"><span className="upload-arrow">↑</span></div><div className="mt-4 font-medium">Drop evidence or click to browse</div><div className="mt-1 text-xs text-ink/50">Up to 12 files · 15 MB each</div></label>{files.length>0&&<div className="mt-4 space-y-2">{files.map((f,i)=><div key={f.name} className="file-in rounded-xl bg-ink/[.035] px-3 py-2 text-xs" style={{animationDelay:`${i*70}ms`}}><span className="truncate">{f.name}</span><span className="font-mono text-ink/45">{(f.size/1024).toFixed(0)} KB</span></div>)}</div>}{error&&<div className="mt-4 rounded-xl border border-red-500/20 bg-red-50 px-3 py-2 text-sm text-red-700">{error}</div>}<button disabled={!files.length||busy} onClick={analyze} className="mt-5 w-full overflow-hidden rounded-xl bg-ink py-3.5 font-medium text-white transition hover:bg-pulse disabled:opacity-40">{busy?<span className="inline-flex items-center gap-2"><span className="loader"/> Building evidence graph…</span>:'Analyze evidence →'}</button><div className="mt-5 grid grid-cols-4 gap-2">{steps.map(([n,s])=><div key={n} className="pipeline-step rounded-xl bg-mist p-2 text-center"><div className="font-mono text-[9px] text-pulse">{n}</div><div className="mt-1 text-[9px] font-mono tracking-wider">{s}</div></div>)}</div></div></div>
  </section>
  <section className="relative border-y border-ink/10 bg-white/40"><div className="mx-auto grid max-w-7xl gap-6 px-6 py-12 md:grid-cols-4">{steps.map(([n,title,desc],i)=><div key={n} className="reveal-up" style={{animationDelay:`${i*90}ms`}}><div className="font-mono text-xs text-pulse">{n}</div><div className="mt-2 font-display text-xl font-semibold">{title}</div><p className="mt-1 text-sm leading-6 text-ink/55">{desc}</p></div>)}</div></section>
  <footer className="mx-auto max-w-7xl px-6 py-8 text-xs text-ink/40">ProofMesh · Evidence is traced, contradictions are explained, decisions stay human.</footer>
 </main>
}
