'use client'
import {useEffect,useMemo,useState} from 'react'
import Link from 'next/link'
import type {ChangeEvent,ReactNode} from 'react'
import type {ProofCase,Finding} from '@/lib/proofmesh/types'

function prettyPredicate(p:string){const map:Record<string,string>={number:'Document number',name:'Supplier',supplier:'Supplier','supplier name':'Supplier',date:'Document date','order date':'Order date',quantity:'Quantity','total quantity':'Quantity','unit price':'Unit price',total:'Total amount','total amount':'Total amount','grand total':'Total amount','po number':'PO number'};return map[p.toLowerCase()]||p.replaceAll('_',' ')}
function kindLabel(k:string){return k.replaceAll('_',' ')}
function sizeLabel(size:number){if(size<1024)return `${size} bytes`;return size<1024*1024?`${(size/1024).toFixed(1)} KB`:`${(size/1024/1024).toFixed(1)} MB`}
function statusLabel(s:string){return s.replaceAll('_',' ')}

export function ProofCaseClient({initialCase}:{initialCase:ProofCase}){
 const[c,setC]=useState(initialCase),[phone,setPhone]=useState(''),[name,setName]=useState('Supplier contact'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[finding,setFinding]=useState(initialCase.findings.find(f=>f.status==='unresolved')?.id||initialCase.findings[0]?.id||null),[uploading,setUploading]=useState(false),[reverifying,setReverifying]=useState(false)
 const selected=c.findings.find(f=>f.id===finding)
 const selectedInvestigation=c.investigations.filter(i=>i.findingId===selected?.id).at(-1)
 const activeInvestigation=!!selectedInvestigation&&['draft','approved','queued','in_progress'].includes(selectedInvestigation.status)
 const grouped=useMemo(()=>c.claims.reduce<Record<string,typeof c.claims>>((m,x)=>{(m[x.sourceName]??=[]).push(x);return m},{}),[c.claims])
 const selectedClaims=new Set(selected?.claimIds||[])
 const quantityByKind=useMemo(()=>{const out:Record<string,string|number|undefined>={};for(const d of c.documents){const q=c.claims.find(x=>x.sourceId===d.id&&x.type==='quantity');if(q)out[d.kind]=q.value}return out},[c.documents,c.claims])
 const po=quantityByKind.purchase_order,invoice=quantityByKind.invoice,delivery=quantityByKind.delivery
 const hasQuantityTriplet=po!==undefined&&invoice!==undefined&&delivery!==undefined
 useEffect(()=>{if(!selectedInvestigation?.callId||!activeInvestigation)return;const t=setInterval(async()=>{const r=await fetch(`/api/proofmesh/case/${c.id}/investigate/status?investigationId=${encodeURIComponent(selectedInvestigation.id)}`);if(r.ok){const d=await r.json();setC(d.case)}},3000);return()=>clearInterval(t)},[c.id,selectedInvestigation?.id,selectedInvestigation?.callId,activeInvestigation])

 async function investigate(){if(!selected||!phone||activeInvestigation)return;setBusy(true);setMessage('Preparing a human-approved investigation…');const r=await fetch(`/api/proofmesh/case/${c.id}/investigate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({findingId:selected.id,phone,contactName:name,region:'IN',locale:'en-IN'})});const d=await r.json();setC(d.case||c);setMessage(r.ok?(d.message||'CALL-E investigation queued.'):d.error||'Investigation failed');setBusy(false)}
 async function addEvidence(e:ChangeEvent<HTMLInputElement>){const files=Array.from(e.target.files||[]);if(!files.length)return;setUploading(true);setMessage('Adding supporting evidence…');const form=new FormData();files.forEach(f=>form.append('files',f));const r=await fetch(`/api/proofmesh/case/${c.id}/supporting-evidence`,{method:'POST',body:form});const d=await r.json();if(!r.ok){setMessage(d.error||'Upload failed')}else if(d.added===0){setC(d.case);setMessage('No new evidence was added. Duplicate files were skipped.')}else{setC(d.case);setMessage('Supporting evidence added. Re-verifying the case…');setReverifying(true);const rr=await fetch(`/api/proofmesh/case/${c.id}/reverify`,{method:'POST'});const rd=await rr.json();setC(rd.case||d.case);setMessage(rr.ok?'Verification complete — the evidence graph and findings were refreshed.':rd.error||'Re-verification failed');setReverifying(false)}setUploading(false);e.target.value=''}
 async function manualReverify(){setReverifying(true);const r=await fetch(`/api/proofmesh/case/${c.id}/reverify`,{method:'POST'});const d=await r.json();setC(d.case||c);setMessage(r.ok?'Verification complete.':'Re-verification failed.');setReverifying(false)}
 async function decide(decision:'resolved'|'rejected'){if(!selected)return;const reason=window.prompt(`Why are you marking this finding ${decision}?`);if(!reason?.trim())return;const r=await fetch(`/api/proofmesh/case/${c.id}/decision`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({findingId:selected.id,decision,reason})});const d=await r.json();if(r.ok)setC(d.case);else setMessage(d.error||'Decision failed')}

 return <main className="min-h-screen overflow-hidden bg-mist text-ink"><div className="case-grid pointer-events-none fixed inset-0"/>
 <header className="sticky top-0 z-30 border-b border-ink/10 bg-mist/80 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><Link href="/" className="font-display text-xl font-semibold">Proof<span className="text-pulse">Mesh</span></Link><div className="flex items-center gap-3"><span className="hidden rounded-full bg-white/70 px-3 py-1.5 font-mono text-[10px] uppercase tracking-[.14em] text-ink/50 sm:inline">Case {c.id.slice(0,8)}</span><Link href="/" className="rounded-lg border border-ink/10 bg-white px-3 py-2 text-xs font-medium transition hover:border-pulse/40">+ New case</Link></div></div></header>
 <div className="relative mx-auto max-w-7xl px-6 py-8"><div className="flex flex-wrap items-end justify-between gap-5 reveal-up"><div><div className="font-mono text-[10px] uppercase tracking-[.18em] text-pulse">Evidence readiness workspace</div><h1 className="mt-2 font-display text-4xl font-semibold tracking-tight md:text-5xl">{c.name}</h1><p className="mt-2 text-ink/55">Trace evidence · verify contradictions · investigate unresolved claims · decide with context</p></div><div className="grid grid-cols-4 gap-2">{[['Docs',c.documents.length],['Claims',c.summary.totalClaims],['Findings',c.summary.findings],['Open',c.summary.unresolved]].map(x=><div key={x[0]} className="stat-card rounded-xl border border-ink/10 bg-white/80 px-4 py-3"><div className="font-mono text-[9px] uppercase text-ink/40">{x[0]}</div><div className="mt-1 text-2xl font-display font-semibold">{x[1]}</div></div>)}</div></div>
 <div className="mt-5 grid gap-2 sm:grid-cols-4"><Flow label="COLLECT" done/><Flow label="EXTRACT" done/><Flow label="VERIFY" done/><Flow label="RESOLVE" active={c.summary.unresolved===0&&c.findings.length>0||!!selectedInvestigation}/></div>
 {!hasQuantityTriplet&&c.findings.length>0&&<div className="mt-6 rounded-2xl border border-pulse/20 bg-white/80 p-5 shadow-sm reveal-up"><div className="flex items-start gap-4"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-pulse text-white font-bold">!</div><div><div className="font-mono text-[10px] uppercase tracking-[.16em] text-pulse">Plain-language evidence summary</div><h2 className="mt-1 text-lg font-semibold">ProofMesh found {c.findings.length} issue{c.findings.length===1?'':'s'} requiring review.</h2><p className="mt-2 text-sm leading-6 text-ink/60">The findings below identify which evidence conflicts or is missing, what additional proof is needed, and the next review action. They are not automatic fraud or approval decisions.</p></div></div></div>}
 {hasQuantityTriplet&&<div className="mt-6 rounded-2xl border border-pulse/20 bg-white/80 p-5 shadow-sm reveal-up"><div className="flex flex-wrap items-start gap-4"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-pulse text-white font-bold">!</div><div className="min-w-0 flex-1"><div className="font-mono text-[10px] uppercase tracking-[.16em] text-pulse">Plain-language evidence summary</div><h2 className="mt-1 text-lg font-semibold">ProofMesh found a quantity mismatch across the supplied documents.</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-ink/60">The purchase order records <b className="text-ink">{po} units</b>, the invoice records <b className="text-ink">{invoice} units</b>, and the delivery note records <b className="text-ink">{delivery} units</b>. This does not by itself establish fraud or an incorrect document. It means the evidence set needs reconciliation.</p><div className="mt-4 grid gap-2 sm:grid-cols-3"><Delta label="Invoice vs PO" value={Number(invoice)-Number(po)}/><Delta label="PO vs delivery" value={Number(delivery)-Number(po)}/><Delta label="Invoice vs delivery" value={Number(invoice)-Number(delivery)}/></div></div></div></div>}
 <div className="mt-8 grid gap-6 xl:grid-cols-[1fr_1.15fr]"><section className="space-y-6">
 <Panel title="Evidence intake"><div className="space-y-3">{c.documents.map((d,i)=><div key={d.id} className="doc-card rounded-2xl border border-ink/10 bg-white p-4" style={{animationDelay:`${i*70}ms`}}><div className="flex justify-between gap-3"><div><div className="font-medium">{d.name}</div><div className="mt-1 font-mono text-[10px] uppercase tracking-wider text-ink/45">{kindLabel(d.kind)} · {sizeLabel(d.size)}</div></div><div className="grid h-8 w-8 place-items-center rounded-lg bg-glow/50">✓</div></div><details className="mt-3"><summary className="cursor-pointer text-xs text-ink/45">Provenance · SHA-256</summary><div className="mt-2 break-all font-mono text-[10px] text-ink/50">{d.sha256}</div><div className="mt-2 text-[10px] text-ink/45">SHA-256 is a fingerprint of this exact uploaded file.</div></details></div>)}</div></Panel>
 <Panel title="Extracted claims"><div className="mb-4 rounded-xl bg-mist/70 p-3 text-xs leading-5 text-ink/55"><b className="text-ink">A claim</b> is one piece of information extracted from a source document. ProofMesh keeps each claim linked to where it came from.</div><div className="mb-3 flex flex-wrap gap-2 text-[10px] font-mono"><span className="claim-badge ai">AI · extracted</span><span className="claim-badge rule">RULE · extracted</span><span className="claim-badge call">CALL-E · supplier statement · unverified</span></div><div className="space-y-4">{Object.entries(grouped).map(([doc,claims])=><div key={doc}><div className="font-mono text-[10px] uppercase tracking-wider text-ink/45">{doc}</div><div className="mt-2 space-y-1">{claims.map(x=><div key={x.id} className={`claim-row flex justify-between gap-4 rounded-lg px-3 py-2 text-sm ${selectedClaims.has(x.id)?'claim-highlight':''}`}><span><span>{prettyPredicate(x.predicate)}</span><small className="ml-2 text-[9px] uppercase tracking-wider text-ink/35">{x.extractedBy==='gemini'?'AI':x.extractedBy==='call'?'CALL-E':'RULE'}</small></span><b>{String(x.value)} {x.unit||''}</b></div>)}</div></div>)}</div></Panel>
 </section><section className="space-y-6">
 <Panel title="Evidence graph"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><div className="text-sm font-semibold">How the evidence is connected</div><p className="mt-1 text-xs text-ink/50">Selecting a finding highlights the claims involved so the reviewer can trace the discrepancy back to its sources.</p></div><span className="rounded-full bg-mist px-3 py-1 text-[10px] font-mono text-ink/50">{c.edges.length} links · {c.nodes.length} nodes</span></div><div className="graph-shell relative min-h-[430px] overflow-hidden rounded-2xl bg-ink p-5"><div className="graph-glow"/><div className="scan-line absolute left-0 right-0 top-0 h-px bg-pulse/90"/><div className="relative grid gap-4 md:grid-cols-3">{c.documents.map(d=>{const docClaims=c.claims.filter(x=>x.sourceId===d.id);return <div key={d.id} className="graph-column"><div className="graph-doc-card"><span className="node-dot"/><div className="text-[10px] uppercase tracking-wider text-white/40">{kindLabel(d.kind)}</div><div className="mt-1 text-sm font-semibold text-white">{d.name}</div><div className="mt-2 text-xs text-white/55">{docClaims.length} extracted claims</div></div><div className="mt-3 space-y-2">{docClaims.slice(0,6).map(x=>{const hit=selectedClaims.has(x.id);return <div key={x.id} className={`graph-claim ${hit?'graph-node-hit':''}`}><span>{prettyPredicate(x.predicate)}</span><b>{String(x.value)}{x.unit?' '+x.unit:''}</b></div>})}</div></div>})}</div><div className="absolute bottom-4 left-5 right-5 flex justify-between font-mono text-[9px] uppercase tracking-wider text-white/35"><span>Source → claim provenance preserved</span><span>{c.nodes.length} nodes</span></div></div></Panel>
 <Panel title="Findings & resolution"><div className="mb-4 rounded-2xl border border-amber-200 bg-amber-50 p-4"><div className="flex items-center justify-between gap-3"><div><div className="font-mono text-[10px] uppercase tracking-wider text-amber-700/70">Evidence review status</div><div className="mt-1 text-base font-semibold text-amber-950">{c.summary.unresolved>0?'Needs human review':'No open findings'}</div></div><div className="rounded-full bg-white/80 px-3 py-1 text-xs font-semibold text-amber-900">{c.summary.unresolved} open</div></div>{c.summary.unresolved>0&&<p className="mt-2 text-xs leading-5 text-amber-900/70">ProofMesh has identified issues to reconcile. A finding is not a final fraud or approval decision.</p>}</div><div className="space-y-3">{c.findings.length===0&&<div className="rounded-xl bg-glow/30 p-4">No contradictions detected in the supplied evidence.</div>}{c.findings.map((f,i)=><FindingCard key={f.id} f={f} selected={finding===f.id} onClick={()=>setFinding(f.id)} index={i}/>)}</div></Panel>
 {selected&&<Panel title="Human-approved CALL-E investigation"><div className="rounded-2xl bg-ink p-5 text-white"><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-wider text-white/45"><span className="h-2 w-2 rounded-full bg-pulse"/> Investigation target</div><p className="mt-3 text-sm leading-6">{selected.explanation}</p><p className="mt-3 rounded-xl border border-white/10 bg-white/5 p-3 text-xs leading-5 text-white/60"><b className="text-white">Trust boundary:</b> CALL-E collects a supplier statement. A phone response is not documentary proof and is never treated as verified evidence until supporting documents are checked.</p></div>{!selectedInvestigation?.supplierClaim&&<><div className="grid gap-3 mt-4 sm:grid-cols-2"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Contact name" className="rounded-xl border border-ink/10 bg-white px-3 py-3 text-sm outline-none focus:border-pulse"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+91..." className="rounded-xl border border-ink/10 bg-white px-3 py-3 text-sm outline-none focus:border-pulse"/></div><button disabled={busy||!phone||activeInvestigation} onClick={investigate} className="mt-3 w-full rounded-xl bg-pulse py-3 font-medium text-white transition hover:-translate-y-0.5 hover:shadow-lg hover:shadow-pulse/20 disabled:opacity-40">{busy?'Starting investigation…':activeInvestigation?'CALL-E investigation active…':'Approve & investigate with CALL-E'}</button><div className="mt-2 text-center text-[10px] text-ink/40">This action places a real phone call when CALL-E is configured. Review the number before approving.</div></>}
 {message&&<div className="mt-3 rounded-xl bg-mist px-3 py-2 text-xs text-ink/60">{message}</div>}
 {selectedInvestigation&&<div className="mt-5 rounded-2xl border border-ink/10 bg-white p-4"><div className="flex items-center justify-between"><div className="font-mono text-[10px] uppercase tracking-wider text-ink/40">Investigation status</div><span className={`status ${selectedInvestigation.status}`}>{statusLabel(selectedInvestigation.status)}</span></div>{selectedInvestigation.supplierClaim&&<div className="mt-4 rounded-xl border border-amber-300 bg-amber-50 p-4"><div className="claim-badge call">UNVERIFIED · SUPPLIER STATEMENT</div><p className="mt-2 text-sm leading-6">{selectedInvestigation.supplierClaim}</p></div>}{selectedInvestigation.requestedEvidence?.map(x=><div key={x} className="mt-2 rounded-lg bg-mist px-3 py-2 text-xs">Requested evidence: <b>{x}</b></div>)}{selectedInvestigation.supplierClaim&&<><div className="mt-4 flex flex-wrap gap-2"><label className="cursor-pointer rounded-xl bg-ink px-4 py-2.5 text-xs font-medium text-white transition hover:bg-pulse">{uploading?'Uploading…':'Upload supporting evidence'}<input multiple type="file" accept=".pdf,.docx,.txt,.csv,.json,.md" className="hidden" onChange={addEvidence}/></label><button disabled={reverifying||uploading} onClick={manualReverify} className="rounded-xl border border-ink/10 px-4 py-2.5 text-xs font-medium hover:border-pulse/40">{reverifying?'Re-verifying…':'Re-verify evidence'}</button></div><p className="mt-2 text-[10px] leading-4 text-ink/40">Supporting evidence is what can change a finding during re-verification; the supplier statement alone cannot.</p></>}</div>}
 {selected.status==='unresolved'&&selectedInvestigation?.supplierClaim&&!activeInvestigation&&<div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>decide('resolved')} className="rounded-xl bg-glow px-3 py-3 text-xs font-semibold">Mark supported / resolved</button><button onClick={()=>decide('rejected')} className="rounded-xl border border-red-200 bg-red-50 px-3 py-3 text-xs font-semibold text-red-700">Reject finding</button></div>}
 </Panel>}
 </section></div></div></main>
}
function Delta({label,value}:{label:string,value:number}){return <div className="rounded-xl bg-mist p-3"><div className="text-[10px] uppercase text-ink/40">{label}</div><div className={`mt-1 font-semibold ${value===0?'text-ink':'text-pulse'}`}>{value>0?'+':''}{value} units</div></div>}
function FindingCard({f,selected,onClick,index}:{f:Finding;selected:boolean;onClick:()=>void;index:number}){return <button onClick={onClick} className={`finding-card w-full text-left rounded-2xl border p-5 ${selected?'border-pulse bg-pulse/5':'border-ink/10 bg-white hover:border-pulse/40'}`} style={{animationDelay:`${index*70}ms`}}><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="font-mono text-[9px] uppercase tracking-[.16em] text-ink/40">Finding {index+1}</div><div className="mt-1 text-base font-semibold">{f.title}</div></div><span className={`status ${f.status}`}>{statusLabel(f.status)}</span></div><div className="mt-4 rounded-xl border border-ink/10 bg-mist/60 p-4"><div className="text-[10px] font-mono uppercase tracking-wider text-ink/40">What ProofMesh found</div><p className="mt-2 text-sm leading-6 text-ink/70">{f.explanation}</p></div>{(f.status==='unresolved'||f.status==='investigating')&&f.missingEvidence.length>0&&<div className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-4"><div className="text-[10px] font-mono uppercase tracking-wider text-amber-700/70">Evidence still needed</div>{f.missingEvidence.map(x=><div key={x} className="mt-1 text-sm text-amber-900">• {x}</div>)}</div>}{(f.status==='unresolved'||f.status==='investigating')&&f.recommendedAction&&<div className="mt-3 rounded-xl border border-blue-100 bg-blue-50 p-4"><div className="text-[10px] font-mono uppercase tracking-wider text-blue-700/70">Recommended next step</div><p className="mt-1 text-sm leading-6 text-blue-950">{f.recommendedAction}</p></div>}{f.resolution&&<div className="mt-3 rounded-xl bg-glow/30 p-3 text-xs text-ink/60"><b>Resolution:</b> {f.resolution}</div>}</button>}
function Flow({label,done,active}:{label:string;done?:boolean;active?:boolean}){return <div className={`flow-item ${done?'done':''} ${active?'active':''}`}><span>{done?'✓':active?'•':'○'}</span>{label}</div>}
function Panel({title,children}:{title:string;children:ReactNode}){return <section className="rounded-[1.5rem] border border-ink/10 bg-white/65 p-5 shadow-sm backdrop-blur-sm transition hover:shadow-md"><div className="mb-4 font-mono text-[10px] uppercase tracking-[.16em] text-ink/45">{title}</div>{children}</section>}
